[modbus]
ip = "10.18.40.60"
port = 502 #optional
uid = 0 #optional

[influx]
host = "http://10.18.40.35:8086"
org = "apartmenthaus"
bucket = "pv"
token = "bscuaMho7z_DzDa9OfGNhnDCI-Mdr1uxsghGip12GcsHiOxoucYkPL7CJYx3rN7l3nNBr-c8BstQrEWH7pH4Dw=="

[general]
refresh_ms = 1000 #optional
log_level = "info" #optional

[[register]]
name = "Input power"
register_number = 40521
datatype = "u32"

[[register]]
name = "Active power"
register_number = 40525
datatype = "u32"

[[register]]
name = "Power factor"
register_number = 40532
datatype = "i16" #i16
gain = 1000 #optional

[[register]]
name = "Reactive power"
register_number = 40544
datatype = "i32" #i32

[[register]]
name = "DC current"
register_number = 40500
datatype = "u16"
gain = 10

[[register]]
name = "DC current 2"
register_number = 40554
datatype = "i32"
gain = 10

[[register]]
name = "Total energy yield"
register_number = 40560
datatype = "u32"
gain = 10

[[register]]
name = "Yield today"
register_number = 40562
datatype = "u32"
gain = 10

[[register]]
name = "Today'spower generation hours"
register_number = 40564
datatype = "u32"
gain = 10

[[register]]
name = "Phase A current of grid"
register_number = 40572
datatype = "i16" #i16

[[register]]
name = "Phase B current of grid"
register_number = 40573
datatype = "i16" #i16

[[register]]
name = "Phase C current of grid"
register_number = 40574
datatype = "i16" #i16

[[register]]
name = "A-B line voltage of grid"
register_number = 40575
datatype = "u16"
gain = 10

[[register]]
name = "B-C line voltage of grid"
register_number = 40576
datatype = "u16"
gain = 10

[[register]]
name = "C-A line voltage of grid"
register_number = 40577
datatype = "u16"
gain = 10

[[register]]
name = "Inverter efficiency"
register_number = 40685
datatype = "u16"
gain = 1000

[[register]]
name = "Local time"
register_number = 40009
datatype = "u32"
